// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExampleParamsType } from "./Param";

export type PluginMessage = "Pong" | { "ParameterChange": ExampleParamsType };
